name: Backend App CI

on:
  push:
    branches: [ master ]
    paths:
    - 'twitter_url_extractor_backend/**'
  pull_request:
    branches: [ master ]
    paths:
    - 'twitter_url_extractor_backend/**'

env:
  RAILS_ENV: test

defaults:
  run:
    working-directory: twitter_url_extractor_backend

jobs:
  ruby_dependencies:
    name: Ruby - download and cache dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Ruby version specified in `.ruby-version`
        uses: eregon/use-ruby-action@master
        with:
          working-directory: twitter_url_extractor_backend

      - name: Ruby gem cache
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: ${{ runner.os }}-gems-

      - name: Install gems
        run: bundle install --jobs 4 --retry 3 --path vendor/bundle

  rspec:
    name: Run RSpec
    runs-on: ubuntu-latest
    needs: ruby_dependencies

    services:
      postgres:
        image: postgres:12.3-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Ruby version specified in `.ruby-version`
        uses: eregon/use-ruby-action@master
        with:
          working-directory: twitter_url_extractor_backend

      - name: Ruby gem cache
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: ${{ runner.os }}-gems-

      - name: Install gems
        run: bundle install --jobs 4 --retry 3 --path vendor/bundle

      - name: Setup test database
        run: bundle exec rails db:create db:migrate

      - name: Run RSpec
        run: bundle exec rspec

  rubocop:
    name: Run Rubocop
    runs-on: ubuntu-latest
    needs: ruby_dependencies

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Ruby version specified in `.ruby-version`
        uses: eregon/use-ruby-action@master
        with:
          working-directory: twitter_url_extractor_backend

      - name: Ruby gem cache
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: ${{ runner.os }}-gems-

      - name: Install gems
        run: bundle install --jobs 4 --retry 3 --path vendor/bundle

      - name: Run Rubocop
        run: bundle exec rubocop

  deploy:
    name: Deploy to Heroku
    runs-on: ubuntu-latest
    needs: [rspec, rubocop]

    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.4.6 # This is the action
        with:
          appdir: twitter_url_extractor_backend
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: twitter-url-extractor-backend
          heroku_email: ${{secrets.HEROKU_EMAIL}}
