name: CI

on:
  push:
    branches: [ master ]
    paths:
    - twitter_url_extractor_client/**
  pull_request:
    branches: [ master ]
    paths:
    - twitter_url_extractor_client/**

env:
  RAILS_ENV: test

jobs:
  ruby_dependencies:
    name: Ruby - download and cache dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Ruby version specified in `.ruby-version`
        uses: eregon/use-ruby-action@master

      - name: Ruby gem cache
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: ${{ runner.os }}-gems-

      - name: Install gems
        run: bundle install --jobs 4 --retry 3 --path vendor/bundle

  rspec:
    name: Run RSpec
    runs-on: ubuntu-latest
    needs: ruby_dependencies

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Ruby version specified in `.ruby-version`
        uses: eregon/use-ruby-action@master

      - name: Ruby gem cache
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: ${{ runner.os }}-gems-

      - name: Install gems
        run: bundle install --jobs 4 --retry 3 --path vendor/bundle

      - name: Run RSpec
        run: bundle exec rspec

  rubocop:
    name: Run Rubocop
    runs-on: ubuntu-latest
    needs: ruby_dependencies

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Ruby version specified in `.ruby-version`
        uses: eregon/use-ruby-action@master

      - name: Ruby gem cache
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: ${{ runner.os }}-gems-

      - name: Install gems
        run: bundle install --jobs 4 --retry 3 --path vendor/bundle

      - name: Run Rubocop
        run: bundle exec rubocop
